devise を使ってユーザー認証を実装する
zecky1120/fjord-books_app-2023 pull request #3
Opened 2024-04-01 04:37 UTC by zecky1120

2024-04-06 12:52 UTC, u1tnk requested changes

2024-04-06 12:52 UTC, u1tnk commented on app/controllers/users/registrations_controller.rb
> +  # before_action :configure_sign_up_params, only: [:create]
コメントアウトしたものはノイズにしかならないので消すようにしましょう。

2024-04-06 12:52 UTC, u1tnk commented on app/views/books/index.html.erb
> -<p style="color: green"><%= notice %></p>
この部分を消した理由はなんですか？

2024-04-06 12:52 UTC, u1tnk commented on app/views/books/index.html.erb
> -
だいぶ細かいので参考までで良いのですが、こういう意味の無い差分があると、なぜ？って言われがちなのであんまり意味無いんだと思いますが気をつけましょう。

2024-04-06 12:52 UTC, u1tnk commented on app/views/devise/passwords/edit.html.erb
> +    <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
autoforcus,autocompleteはテンプレートにあったと思いますが、どういう動作をしているでしょうか？

2024-04-07 10:08 UTC, zecky1120 commented on app/views/books/index.html.erb
> -<p style="color: green"><%= notice %></p>
`<%= notice %>`の箇所は`application.html.erb`に移動した方が一括管理出来て良いかなと思ったのですが、移動させないほうが良かったでしょうか。

2024-04-07 10:15 UTC, zecky1120 commented on app/views/books/index.html.erb
> -
ありがとうございます！

2024-04-07 10:40 UTC, zecky1120 commented on app/views/devise/passwords/edit.html.erb
> +    <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
- autofocus
ページを読み込んだらすぐにautofocus属性を記述している部分にカーソルが移動して入力状態になる、というものです。
https://www.awesomescreenshot.com/video/26504157?key=2f627921bcad6dbcde7eead3af1b311a
- autocomplete
ブラウザに入力したIDやパスワードを記録して自動補完してくれる機能です。

2024-04-07 10:41 UTC, zecky1120 commented
@u1tnk 
ご確認ありがとうございました！　コメント記載しましたのでご確認いただけたらと思います！

2024-04-07 13:33 UTC, u1tnk approved these changes
コメントアウトの指摘は普通に消して欲しかったですが…まあ本プラクティスの主題でも無いし良しとしましょう。
次から気をつけてください。

2024-04-07 13:33 UTC, u1tnk commented on app/views/books/index.html.erb
> -<p style="color: green"><%= notice %></p>
いえ、ざっと見てよくわからなかったので質問しただけです。

noticeが無い場合も囲んでるタグを出力しちゃってるので必要無い画面でも出てるとしたらあんまり良く無いかなーぐらいですね。

まあ修正するほどでも無いです。

2024-04-09 05:44 UTC, merged